import type { CircuitState, CircuitGate } from "./circuit"

/**
 * Generate valid, runnable Qiskit Python code for the given circuit.
 * Output targets Qiskit 1.x + qiskit-aer for local simulation,
 * and is compatible with IBM Quantum via qiskit-ibm-runtime.
 */
export function toQiskit(circuit: CircuitState): string {
  const { numQubits, gates } = circuit

  const lines: string[] = [
    "from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister",
    "from qiskit_aer import AerSimulator",
    "",
    `# ${numQubits}-qubit circuit generated by QuantumLearn`,
    `qr = QuantumRegister(${numQubits}, 'q')`,
    `cr = ClassicalRegister(${numQubits}, 'c')`,
    `qc = QuantumCircuit(qr, cr)`,
    "",
  ]

  if (gates.length === 0) {
    lines.push("# (empty circuit — all qubits initialised to |0⟩)")
    lines.push("")
  } else {
    // Sort by column, then qubit, so the output reads left-to-right
    const sorted = [...gates].sort(
      (a, b) => a.column - b.column || a.qubit - b.qubit,
    )

    let prevCol = -1
    for (const gate of sorted) {
      if (gate.column !== prevCol) {
        if (prevCol !== -1) lines.push("")
        prevCol = gate.column
      }
      lines.push(gateToQiskit(gate))
    }
    lines.push("")
  }

  lines.push("# Measure all qubits into classical register")
  lines.push("qc.measure(qr, cr)")
  lines.push("")
  lines.push("# Simulate locally with Aer")
  lines.push("simulator = AerSimulator()")
  lines.push("job = simulator.run(qc, shots=1024)")
  lines.push("result = job.result()")
  lines.push("counts = result.get_counts()")
  lines.push("print(counts)")
  lines.push("")
  lines.push("# Draw the circuit (requires matplotlib)")
  lines.push("# qc.draw('mpl')")

  return lines.join("\n")
}

/** Map a single CircuitGate to its Qiskit method call. */
function gateToQiskit(gate: CircuitGate): string {
  const q = gate.qubit
  const t = gate.targetQubit ?? q + 1
  const theta = (gate.param ?? Math.PI / 2).toFixed(6)

  switch (gate.gateId) {
    case "H":    return `qc.h(qr[${q}])`
    case "X":    return `qc.x(qr[${q}])`
    case "Y":    return `qc.y(qr[${q}])`
    case "Z":    return `qc.z(qr[${q}])`
    case "S":    return `qc.s(qr[${q}])`
    case "T":    return `qc.t(qr[${q}])`
    case "I":    return `qc.id(qr[${q}])`
    case "CNOT": return `qc.cx(qr[${q}], qr[${t}])`
    case "CZ":   return `qc.cz(qr[${q}], qr[${t}])`
    case "SWAP": return `qc.swap(qr[${q}], qr[${t}])`
    case "Rx":   return `qc.rx(${theta}, qr[${q}])`
    case "Ry":   return `qc.ry(${theta}, qr[${q}])`
    case "Rz":   return `qc.rz(${theta}, qr[${q}])`
    default:     return `# Unsupported gate: ${gate.gateId}`
  }
}

/** Lightweight Python syntax highlighter — returns HTML string. */
export function highlightPython(code: string): string {
  const KEYWORDS = /\b(from|import|as|if|else|elif|def|class|return|for|in|while|with|try|except|pass|True|False|None)\b/g
  const STRINGS  = /("""[\s\S]*?"""|'''[\s\S]*?'''|"[^"\n]*"|'[^'\n]*')/g
  const COMMENTS = /(#[^\n]*)/g
  const NUMBERS  = /\b(\d+\.?\d*)\b/g
  const BUILTINS = /\b(print|len|range|str|int|float|list|dict|tuple|set)\b/g

  // Escape HTML first
  let out = code
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")

  // Apply highlighting in order (comments last so they override everything)
  out = out.replace(NUMBERS,  (m) => `<span class="hl-num">${m}</span>`)
  out = out.replace(BUILTINS, (m) => `<span class="hl-builtin">${m}</span>`)
  out = out.replace(KEYWORDS, (m) => `<span class="hl-kw">${m}</span>`)
  out = out.replace(STRINGS,  (m) => `<span class="hl-str">${m}</span>`)
  out = out.replace(COMMENTS, (m) => `<span class="hl-comment">${m}</span>`)

  return out
}
